from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ErrorModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, detail=None, status=None, type=None):  # noqa: E501
        """ErrorModel - a model defined in OpenAPI

        :param title: The title of this ErrorModel.  # noqa: E501
        :type title: str
        :param detail: The detail of this ErrorModel.  # noqa: E501
        :type detail: str
        :param status: The status of this ErrorModel.  # noqa: E501
        :type status: int
        :param type: The type of this ErrorModel.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'title': str,
            'detail': str,
            'status': int,
            'type': str
        }

        self.attribute_map = {
            'title': 'title',
            'detail': 'detail',
            'status': 'status',
            'type': 'type'
        }

        self._title = title
        self._detail = detail
        self._status = status
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorModel of this ErrorModel.  # noqa: E501
        :rtype: ErrorModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this ErrorModel.


        :return: The title of this ErrorModel.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this ErrorModel.


        :param title: The title of this ErrorModel.
        :type title: str
        """

        self._title = title

    @property
    def detail(self) -> str:
        """Gets the detail of this ErrorModel.


        :return: The detail of this ErrorModel.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail: str):
        """Sets the detail of this ErrorModel.


        :param detail: The detail of this ErrorModel.
        :type detail: str
        """

        self._detail = detail

    @property
    def status(self) -> int:
        """Gets the status of this ErrorModel.


        :return: The status of this ErrorModel.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this ErrorModel.


        :param status: The status of this ErrorModel.
        :type status: int
        """

        self._status = status

    @property
    def type(self) -> str:
        """Gets the type of this ErrorModel.


        :return: The type of this ErrorModel.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ErrorModel.


        :param type: The type of this ErrorModel.
        :type type: str
        """

        self._type = type
