from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class FileResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, filename=None, upload_date=None, video_url=None, image_url=None):  # noqa: E501
        """FileResponse - a model defined in OpenAPI

        :param id: The id of this FileResponse.  # noqa: E501
        :type id: str
        :param filename: The filename of this FileResponse.  # noqa: E501
        :type filename: str
        :param upload_date: The upload_date of this FileResponse.  # noqa: E501
        :type upload_date: datetime
        :param video_url: The video_url of this FileResponse.  # noqa: E501
        :type video_url: str
        :param image_url: The image_url of this FileResponse.  # noqa: E501
        :type image_url: str
        """
        self.openapi_types = {
            'id': str,
            'filename': str,
            'upload_date': datetime,
            'video_url': str,
            'image_url': str
        }

        self.attribute_map = {
            'id': 'id',
            'filename': 'filename',
            'upload_date': 'upload_date',
            'video_url': 'video_url',
            'image_url': 'image_url'
        }

        self._id = id
        self._filename = filename
        self._upload_date = upload_date
        self._video_url = video_url
        self._image_url = image_url

    @classmethod
    def from_dict(cls, dikt) -> 'FileResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FileResponse of this FileResponse.  # noqa: E501
        :rtype: FileResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this FileResponse.


        :return: The id of this FileResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this FileResponse.


        :param id: The id of this FileResponse.
        :type id: str
        """

        self._id = id

    @property
    def filename(self) -> str:
        """Gets the filename of this FileResponse.


        :return: The filename of this FileResponse.
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename: str):
        """Sets the filename of this FileResponse.


        :param filename: The filename of this FileResponse.
        :type filename: str
        """

        self._filename = filename

    @property
    def upload_date(self) -> datetime:
        """Gets the upload_date of this FileResponse.


        :return: The upload_date of this FileResponse.
        :rtype: datetime
        """
        return self._upload_date

    @upload_date.setter
    def upload_date(self, upload_date: datetime):
        """Sets the upload_date of this FileResponse.


        :param upload_date: The upload_date of this FileResponse.
        :type upload_date: datetime
        """

        self._upload_date = upload_date

    @property
    def video_url(self) -> str:
        """Gets the video_url of this FileResponse.


        :return: The video_url of this FileResponse.
        :rtype: str
        """
        return self._video_url

    @video_url.setter
    def video_url(self, video_url: str):
        """Sets the video_url of this FileResponse.


        :param video_url: The video_url of this FileResponse.
        :type video_url: str
        """

        self._video_url = video_url

    @property
    def image_url(self) -> str:
        """Gets the image_url of this FileResponse.


        :return: The image_url of this FileResponse.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this FileResponse.


        :param image_url: The image_url of this FileResponse.
        :type image_url: str
        """

        self._image_url = image_url
