from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.job_config import JobConfig
from openapi_server import util

from openapi_server.models.job_config import JobConfig  # noqa: E501

class JobInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, config=None, video_file=None):  # noqa: E501
        """JobInfo - a model defined in OpenAPI

        :param config: The config of this JobInfo.  # noqa: E501
        :type config: JobConfig
        :param video_file: The video_file of this JobInfo.  # noqa: E501
        :type video_file: str
        """
        self.openapi_types = {
            'config': JobConfig,
            'video_file': str
        }

        self.attribute_map = {
            'config': 'config',
            'video_file': 'video_file'
        }

        self._config = config
        self._video_file = video_file

    @classmethod
    def from_dict(cls, dikt) -> 'JobInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobInfo of this JobInfo.  # noqa: E501
        :rtype: JobInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def config(self) -> JobConfig:
        """Gets the config of this JobInfo.


        :return: The config of this JobInfo.
        :rtype: JobConfig
        """
        return self._config

    @config.setter
    def config(self, config: JobConfig):
        """Sets the config of this JobInfo.


        :param config: The config of this JobInfo.
        :type config: JobConfig
        """

        self._config = config

    @property
    def video_file(self) -> str:
        """Gets the video_file of this JobInfo.


        :return: The video_file of this JobInfo.
        :rtype: str
        """
        return self._video_file

    @video_file.setter
    def video_file(self, video_file: str):
        """Sets the video_file of this JobInfo.


        :param video_file: The video_file of this JobInfo.
        :type video_file: str
        """

        self._video_file = video_file
