from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.job_config import JobConfig
from openapi_server import util

from openapi_server.models.job_config import JobConfig  # noqa: E501

class JobRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, video_file=None, config=None):  # noqa: E501
        """JobRequest - a model defined in OpenAPI

        :param video_file: The video_file of this JobRequest.  # noqa: E501
        :type video_file: str
        :param config: The config of this JobRequest.  # noqa: E501
        :type config: JobConfig
        """
        self.openapi_types = {
            'video_file': str,
            'config': JobConfig
        }

        self.attribute_map = {
            'video_file': 'video_file',
            'config': 'config'
        }

        self._video_file = video_file
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'JobRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobRequest of this JobRequest.  # noqa: E501
        :rtype: JobRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def video_file(self) -> str:
        """Gets the video_file of this JobRequest.


        :return: The video_file of this JobRequest.
        :rtype: str
        """
        return self._video_file

    @video_file.setter
    def video_file(self, video_file: str):
        """Sets the video_file of this JobRequest.


        :param video_file: The video_file of this JobRequest.
        :type video_file: str
        """
        if video_file is None:
            raise ValueError("Invalid value for `video_file`, must not be `None`")  # noqa: E501

        self._video_file = video_file

    @property
    def config(self) -> JobConfig:
        """Gets the config of this JobRequest.


        :return: The config of this JobRequest.
        :rtype: JobConfig
        """
        return self._config

    @config.setter
    def config(self, config: JobConfig):
        """Sets the config of this JobRequest.


        :param config: The config of this JobRequest.
        :type config: JobConfig
        """

        self._config = config
