from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class JobParamsSubtitlesFrequency(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, max=None, min=None):  # noqa: E501
        """JobParamsSubtitlesFrequency - a model defined in OpenAPI

        :param max: The max of this JobParamsSubtitlesFrequency.  # noqa: E501
        :type max: int
        :param min: The min of this JobParamsSubtitlesFrequency.  # noqa: E501
        :type min: int
        """
        self.openapi_types = {
            'max': int,
            'min': int
        }

        self.attribute_map = {
            'max': 'max',
            'min': 'min'
        }

        self._max = max
        self._min = min

    @classmethod
    def from_dict(cls, dikt) -> 'JobParamsSubtitlesFrequency':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobParams_subtitles_frequency of this JobParamsSubtitlesFrequency.  # noqa: E501
        :rtype: JobParamsSubtitlesFrequency
        """
        return util.deserialize_model(dikt, cls)

    @property
    def max(self) -> int:
        """Gets the max of this JobParamsSubtitlesFrequency.


        :return: The max of this JobParamsSubtitlesFrequency.
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max: int):
        """Sets the max of this JobParamsSubtitlesFrequency.


        :param max: The max of this JobParamsSubtitlesFrequency.
        :type max: int
        """
        if max is None:
            raise ValueError("Invalid value for `max`, must not be `None`")  # noqa: E501

        self._max = max

    @property
    def min(self) -> int:
        """Gets the min of this JobParamsSubtitlesFrequency.


        :return: The min of this JobParamsSubtitlesFrequency.
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min: int):
        """Sets the min of this JobParamsSubtitlesFrequency.


        :param min: The min of this JobParamsSubtitlesFrequency.
        :type min: int
        """
        if min is None:
            raise ValueError("Invalid value for `min`, must not be `None`")  # noqa: E501

        self._min = min
