from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.job_config import JobConfig
from openapi_server import util

from openapi_server.models.job_config import JobConfig  # noqa: E501

class JobInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, config=None, filename=None):  # noqa: E501
        """JobInfo - a model defined in OpenAPI

        :param config: The config of this JobInfo.  # noqa: E501
        :type config: JobConfig
        :param filename: The filename of this JobInfo.  # noqa: E501
        :type filename: str
        """
        self.openapi_types = {
            'config': JobConfig,
            'filename': str
        }

        self.attribute_map = {
            'config': 'config',
            'filename': 'filename'
        }

        self._config = config
        self._filename = filename

    @classmethod
    def from_dict(cls, dikt) -> 'JobInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobInfo of this JobInfo.  # noqa: E501
        :rtype: JobInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def config(self) -> JobConfig:
        """Gets the config of this JobInfo.


        :return: The config of this JobInfo.
        :rtype: JobConfig
        """
        return self._config

    @config.setter
    def config(self, config: JobConfig):
        """Sets the config of this JobInfo.


        :param config: The config of this JobInfo.
        :type config: JobConfig
        """

        self._config = config

    @property
    def filename(self) -> str:
        """Gets the filename of this JobInfo.


        :return: The filename of this JobInfo.
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename: str):
        """Sets the filename of this JobInfo.


        :param filename: The filename of this JobInfo.
        :type filename: str
        """

        self._filename = filename
