from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.transcription_request import TranscriptionRequest
from openapi_server import util

from openapi_server.models.transcription_request import TranscriptionRequest  # noqa: E501

class TranscriptionPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _schema=None):  # noqa: E501
        """TranscriptionPostRequest - a model defined in OpenAPI

        :param _schema: The _schema of this TranscriptionPostRequest.  # noqa: E501
        :type _schema: TranscriptionRequest
        """
        self.openapi_types = {
            '_schema': TranscriptionRequest
        }

        self.attribute_map = {
            '_schema': 'schema'
        }

        self.__schema = _schema

    @classmethod
    def from_dict(cls, dikt) -> 'TranscriptionPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _transcription_post_request of this TranscriptionPostRequest.  # noqa: E501
        :rtype: TranscriptionPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _schema(self) -> TranscriptionRequest:
        """Gets the _schema of this TranscriptionPostRequest.


        :return: The _schema of this TranscriptionPostRequest.
        :rtype: TranscriptionRequest
        """
        return self.__schema

    @_schema.setter
    def _schema(self, _schema: TranscriptionRequest):
        """Sets the _schema of this TranscriptionPostRequest.


        :param _schema: The _schema of this TranscriptionPostRequest.
        :type _schema: TranscriptionRequest
        """

        self.__schema = _schema
