from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.transcription_data import TranscriptionData
from openapi_server import util

from openapi_server.models.transcription_data import TranscriptionData  # noqa: E501

class TranscriptionPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, transcription_id=None, data=None, job_id=None):  # noqa: E501
        """TranscriptionPost200Response - a model defined in OpenAPI

        :param transcription_id: The transcription_id of this TranscriptionPost200Response.  # noqa: E501
        :type transcription_id: str
        :param data: The data of this TranscriptionPost200Response.  # noqa: E501
        :type data: TranscriptionData
        :param job_id: The job_id of this TranscriptionPost200Response.  # noqa: E501
        :type job_id: str
        """
        self.openapi_types = {
            'transcription_id': str,
            'data': TranscriptionData,
            'job_id': str
        }

        self.attribute_map = {
            'transcription_id': 'transcription_id',
            'data': 'data',
            'job_id': 'job_id'
        }

        self._transcription_id = transcription_id
        self._data = data
        self._job_id = job_id

    @classmethod
    def from_dict(cls, dikt) -> 'TranscriptionPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _transcription_post_200_response of this TranscriptionPost200Response.  # noqa: E501
        :rtype: TranscriptionPost200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transcription_id(self) -> str:
        """Gets the transcription_id of this TranscriptionPost200Response.


        :return: The transcription_id of this TranscriptionPost200Response.
        :rtype: str
        """
        return self._transcription_id

    @transcription_id.setter
    def transcription_id(self, transcription_id: str):
        """Sets the transcription_id of this TranscriptionPost200Response.


        :param transcription_id: The transcription_id of this TranscriptionPost200Response.
        :type transcription_id: str
        """

        self._transcription_id = transcription_id

    @property
    def data(self) -> TranscriptionData:
        """Gets the data of this TranscriptionPost200Response.


        :return: The data of this TranscriptionPost200Response.
        :rtype: TranscriptionData
        """
        return self._data

    @data.setter
    def data(self, data: TranscriptionData):
        """Sets the data of this TranscriptionPost200Response.


        :param data: The data of this TranscriptionPost200Response.
        :type data: TranscriptionData
        """

        self._data = data

    @property
    def job_id(self) -> str:
        """Gets the job_id of this TranscriptionPost200Response.


        :return: The job_id of this TranscriptionPost200Response.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: str):
        """Sets the job_id of this TranscriptionPost200Response.


        :param job_id: The job_id of this TranscriptionPost200Response.
        :type job_id: str
        """

        self._job_id = job_id
