from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.transcription_data import TranscriptionData
from openapi_server import util

from openapi_server.models.transcription_data import TranscriptionData  # noqa: E501

class TranscriptionResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, data=None, job_id=None, filename=None):  # noqa: E501
        """TranscriptionResponse - a model defined in OpenAPI

        :param id: The id of this TranscriptionResponse.  # noqa: E501
        :type id: str
        :param data: The data of this TranscriptionResponse.  # noqa: E501
        :type data: TranscriptionData
        :param job_id: The job_id of this TranscriptionResponse.  # noqa: E501
        :type job_id: str
        :param filename: The filename of this TranscriptionResponse.  # noqa: E501
        :type filename: str
        """
        self.openapi_types = {
            'id': str,
            'data': TranscriptionData,
            'job_id': str,
            'filename': str
        }

        self.attribute_map = {
            'id': 'id',
            'data': 'data',
            'job_id': 'job_id',
            'filename': 'filename'
        }

        self._id = id
        self._data = data
        self._job_id = job_id
        self._filename = filename

    @classmethod
    def from_dict(cls, dikt) -> 'TranscriptionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TranscriptionResponse of this TranscriptionResponse.  # noqa: E501
        :rtype: TranscriptionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this TranscriptionResponse.


        :return: The id of this TranscriptionResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this TranscriptionResponse.


        :param id: The id of this TranscriptionResponse.
        :type id: str
        """

        self._id = id

    @property
    def data(self) -> TranscriptionData:
        """Gets the data of this TranscriptionResponse.


        :return: The data of this TranscriptionResponse.
        :rtype: TranscriptionData
        """
        return self._data

    @data.setter
    def data(self, data: TranscriptionData):
        """Sets the data of this TranscriptionResponse.


        :param data: The data of this TranscriptionResponse.
        :type data: TranscriptionData
        """

        self._data = data

    @property
    def job_id(self) -> str:
        """Gets the job_id of this TranscriptionResponse.


        :return: The job_id of this TranscriptionResponse.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: str):
        """Sets the job_id of this TranscriptionResponse.


        :param job_id: The job_id of this TranscriptionResponse.
        :type job_id: str
        """

        self._job_id = job_id

    @property
    def filename(self) -> str:
        """Gets the filename of this TranscriptionResponse.


        :return: The filename of this TranscriptionResponse.
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename: str):
        """Sets the filename of this TranscriptionResponse.


        :param filename: The filename of this TranscriptionResponse.
        :type filename: str
        """

        self._filename = filename
