from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class VideoGet200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, video_id=None, video_name=None, upload_date=None):  # noqa: E501
        """VideoGet200ResponseInner - a model defined in OpenAPI

        :param video_id: The video_id of this VideoGet200ResponseInner.  # noqa: E501
        :type video_id: str
        :param video_name: The video_name of this VideoGet200ResponseInner.  # noqa: E501
        :type video_name: str
        :param upload_date: The upload_date of this VideoGet200ResponseInner.  # noqa: E501
        :type upload_date: datetime
        """
        self.openapi_types = {
            'video_id': str,
            'video_name': str,
            'upload_date': datetime
        }

        self.attribute_map = {
            'video_id': 'video_id',
            'video_name': 'video_name',
            'upload_date': 'upload_date'
        }

        self._video_id = video_id
        self._video_name = video_name
        self._upload_date = upload_date

    @classmethod
    def from_dict(cls, dikt) -> 'VideoGet200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _video_get_200_response_inner of this VideoGet200ResponseInner.  # noqa: E501
        :rtype: VideoGet200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def video_id(self) -> str:
        """Gets the video_id of this VideoGet200ResponseInner.


        :return: The video_id of this VideoGet200ResponseInner.
        :rtype: str
        """
        return self._video_id

    @video_id.setter
    def video_id(self, video_id: str):
        """Sets the video_id of this VideoGet200ResponseInner.


        :param video_id: The video_id of this VideoGet200ResponseInner.
        :type video_id: str
        """

        self._video_id = video_id

    @property
    def video_name(self) -> str:
        """Gets the video_name of this VideoGet200ResponseInner.


        :return: The video_name of this VideoGet200ResponseInner.
        :rtype: str
        """
        return self._video_name

    @video_name.setter
    def video_name(self, video_name: str):
        """Sets the video_name of this VideoGet200ResponseInner.


        :param video_name: The video_name of this VideoGet200ResponseInner.
        :type video_name: str
        """

        self._video_name = video_name

    @property
    def upload_date(self) -> datetime:
        """Gets the upload_date of this VideoGet200ResponseInner.


        :return: The upload_date of this VideoGet200ResponseInner.
        :rtype: datetime
        """
        return self._upload_date

    @upload_date.setter
    def upload_date(self, upload_date: datetime):
        """Sets the upload_date of this VideoGet200ResponseInner.


        :param upload_date: The upload_date of this VideoGet200ResponseInner.
        :type upload_date: datetime
        """

        self._upload_date = upload_date
